[book]
authors = ["Charles Low"]
description = ""
language = "en"
text-direction = "ltr"
src = "src"
title = "Chux's Notebook"

[output.html]
copy-fonts = true
default_theme = "navy"
additional-css = ["katex.min.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
runnable = false

[preprocessor.katex]
after = ["links"]
macros = "src/macros.txt"

[preprocessor.format]
command = "./format/target/release/format"

[preprocessor.mermaid]
command = "mdbook-mermaid"
